services:
  nginx1:
    image: nginx:alpine
    container_name: nginx1
    ports:
      - "8081:80"
    networks:
      - nginx_net
    command: |
      /bin/sh -c 'echo "<h1>Welcome to Nginx1 (Port 8081)</h1>" > /usr/share/nginx/html/index.html && nginx -g "daemon off;"'

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    ports:
      - "8082:80"
    networks:
      - nginx_net
    command: |
      /bin/sh -c 'echo "<h1>Welcome to Nginx2 (Port 8082)</h1>" > /usr/share/nginx/html/index.html && nginx -g "daemon off;"'

  nginx_proxy:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - nginx1
      - nginx2
    networks:
      - nginx_net
    volumes:
      - ./nginx_rewrite.conf:/etc/nginx/conf.d/default.conf
    command: |
       /bin/sh -c 'nginx -g "daemon off;"'
networks:
  nginx_net:
    driver: bridge
